export const titles: Record<string, string> = {
  ru: '«Аудиоиндукционист»: встреча с посланником подсознания или буддийский наставник?',
  en: '"Audioinductionist": Meeting a Messenger of the Subconscious or a Buddhist Mentor?',
  hi: '"ऑडियोइंडक्शनिस्ट": अवचेतन के संदेशवाहक या बौद्ध गुरु से मुलाकात?',
  es: '"Audioinduccionista": ¿Encuentro con un mensajero del subconsciente o un mentor budista?',
  fr: '« Audioinductionniste » : rencontre avec un messager du subconscient ou un mentor bouddhiste ?',
  de: '„Audioinduktionist": Begegnung mit einem Boten des Unterbewusstseins oder einem buddhistischen Mentor?',
  zh: '「音频归纳者」：与潜意识信使相遇，还是与佛教导师相遇？',
  ja: '「オーディオインダクショニスト」：潜在意識の使者との出会い、それとも仏教の導師？',
  pt: '"Audioinduccionista": Encontro com um mensageiro do subconsciente ou um mentor budista?',
  th: '"นักอุปนัยเสียง": การพบผู้ส่งสารจากจิตใต้สำนึกหรือที่ปรึกษาพุทธศาสนา?',
  vi: '"Người quy nạp âm thanh": Cuộc gặp với sứ giả của tiềm thức hay một người cố vấn Phật giáo?',
  ko: '"오디오귀납주의자": 잠재의식의 전령인가 불교 스승인가?',
  id: '"Audioinduksionis": Bertemu dengan utusan bawah sadar atau mentor Buddhis?',
  ms: '"Audioinduksionis": Pertemuan dengan utusan bawah sedar atau mentor Buddha?',
  si: '"ශ්‍රව්‍ය ප්‍රේරකවාදී": අවිඥානයේ පණිවිඩකරුවෙකු හෝ බෞද්ධ උපදේශකයෙකු හමුවීමක්?',
  my: '"အသံလျှပ်ကူးဝါဒီ": မသိစိတ်တမန်တစ်ဦး (သို့) ဗုဒ္ဓဘာသာဆရာတစ်ဦးနှင့်တွေ့ဆုံခြင်း?',
  ne: '"अडियोइन्डक्सनिस्ट": अवचेतनको सन्देशवाहक वा बौद्ध सल्लाहकार?',
  bo: '«སྒྲ་ཐེབས་ལེན་པ»། མ་རིག་པའི་ཕོ་ཉ། ཡང་ན་སངས་རྒྱས་ཀྱི་བསླབ་བྱོན།',
}

export const subtitles: Record<string, string> = {
  ru: 'Первая статья на сайте Buddha\'s Wisdom Chat',
  en: 'First article on Buddha\'s Wisdom Chat',
  hi: 'Buddha\'s Wisdom Chat पर पहला लेख',
  es: 'Primer artículo en Buddha\'s Wisdom Chat',
  fr: 'Premier article sur Buddha\'s Wisdom Chat',
  de: 'Erster Artikel auf Buddha\'s Wisdom Chat',
  zh: '在 Buddha\'s Wisdom Chat 上的第一篇文章',
  ja: 'Buddha\'s Wisdom Chat 初めての記事',
  pt: 'Primeiro artigo no Buddha\'s Wisdom Chat',
  th: 'บทความแรกบน Buddha\'s Wisdom Chat',
  vi: 'Bài viết đầu tiên trên Buddha\'s Wisdom Chat',
  ko: 'Buddha\'s Wisdom Chat 첫 번째 글',
  id: 'Artikel pertama di Buddha\'s Wisdom Chat',
  ms: 'Artikel pertama di Buddha\'s Wisdom Chat',
  si: 'Buddha\'s Wisdom Chat හි පළමු ලිපිය',
  my: 'Buddha\'s Wisdom Chat ပေါ်ရှိ ပထမဆုံးဆောင်းပါး',
  ne: 'Buddha\'s Wisdom Chat मा पहिलो लेख',
  bo: 'Buddha\'s Wisdom Chat ནང་གི་དང་པོའི་དཔྱད་རྩོམ།',
}

export const sectionHeadings: Record<string, string[]> = {
  ru: [
    'Вступление',
    'Часть 1. Научный взгляд: что такое аудиоиндукционист и индукционист?',
    '1.1. Аудиоиндукционист — техническая версия',
    '1.2. Индукционист (или индуктивист) — философская версия',
    'Часть 2. Буддийский взгляд: индукция, слушание и восход',
    '2.1. Буддийская «индукция» — проверка на себе',
    '2.2. «Аудио» — слушание как практика',
    '2.3. Восход как просветление',
    'Часть 3. Что сказал мой сон? (Символическая расшифровка)',
    'Часть 4. Итог: первая статья как приглашение',
  ],
  en: [
    'Introduction',
    'Part 1. Scientific View: What is an Audioinductionist and Inductionist?',
    '1.1. Audioinductionist — Technical Version',
    '1.2. Inductionist (or Inductivist) — Philosophical Version',
    'Part 2. Buddhist View: Induction, Listening, and Dawn',
    '2.1. Buddhist "Induction" — Testing on Yourself',
    '2.2. "Audio" — Listening as Practice',
    '2.3. Dawn as Enlightenment',
    'Part 3. What Did My Dream Say? (Symbolic Interpretation)',
    'Part 4. Conclusion: First Article as an Invitation',
  ],
  hi: [
    'परिचय',
    'भाग 1. वैज्ञानिक दृष्टिकोण: ऑडियोइंडक्शनिस्ट और इंडक्शनिस्ट क्या है?',
    '1.1. ऑडियोइंडक्शनिस्ट — तकनीकी संस्करण',
    '1.2. इंडक्शनिस्ट (या इंडक्टिविस्ट) — दार्शनिक संस्करण',
    'भाग 2. बौद्ध दृष्टिकोण: इंडक्शन, श्रवण और भोर',
    '2.1. बौद्ध "इंडक्शन" — स्वयं पर परीक्षण',
    '2.2. "ऑडियो" — अभ्यास के रूप में श्रवण',
    '2.3. आत्मज्ञान के रूप में भोर',
    'भाग 3. मेरे सपने ने क्या कहा? (प्रतीकात्मक व्याख्या)',
    'भाग 4. निष्कर्ष: पहला लेख एक निमंत्रण के रूप में',
  ],
  es: [
    'Introducción',
    'Parte 1. Visión científica: ¿Qué es un audioinduccionista y un induccionista?',
    '1.1. Audioinduccionista — Versión técnica',
    '1.2. Induccionista (o inductivista) — Versión filosófica',
    'Parte 2. Visión budista: Inducción, escucha y amanecer',
    '2.1. "Inducción" budista — Comprobación en uno mismo',
    '2.2. "Audio" — La escucha como práctica',
    '2.3. El amanecer como iluminación',
    'Parte 3. ¿Qué dijo mi sueño? (Interpretación simbólica)',
    'Parte 4. Conclusión: Primer artículo como invitación',
  ],
  fr: [
    'Introduction',
    'Partie 1. Regard scientifique : Qu\'est-ce qu\'un audioinductionniste et un inductionniste ?',
    '1.1. Audioinductionniste — Version technique',
    '1.2. Inductionniste (ou inductiviste) — Version philosophique',
    'Partie 2. Regard bouddhiste : Induction, écoute et aube',
    '2.1. « Induction » bouddhiste — Vérification par soi-même',
    '2.2. « Audio » — L\'écoute comme pratique',
    '2.3. L\'aube comme éveil',
    'Partie 3. Qu\'a dit mon rêve ? (Déchiffrement symbolique)',
    'Partie 4. Conclusion : Premier article comme invitation',
  ],
  de: [
    'Einleitung',
    'Teil 1. Wissenschaftliche Sicht: Was ist ein Audioinduktionist und Induktionist?',
    '1.1. Audioinduktionist — Technische Version',
    '1.2. Induktionist (oder Induktivist) — Philosophische Version',
    'Teil 2. Buddhistische Sicht: Induktion, Zuhören und Morgenröte',
    '2.1. Buddhistische "Induktion" — Selbstüberprüfung',
    '2.2. "Audio" — Zuhören als Praxis',
    '2.3. Die Morgenröte als Erleuchtung',
    'Teil 3. Was sagte mein Traum? (Symbolische Deutung)',
    'Teil 4. Fazit: Erster Artikel als Einladung',
  ],
  zh: [
    '引言',
    '第一部分 科学视角：什么是音频归纳者与归纳主义者？',
    '1.1. 音频归纳者 — 技术角度',
    '1.2. 归纳主义者（或归纳论者）— 哲学角度',
    '第二部分 佛教视角：归纳、听闻与觉悟',
    '2.1. 佛教的"归纳法" — 自我验证',
    '2.2. "音频" — 听闻即修行',
    '2.3. 觉悟如黎明',
    '第三部分 我的梦说了什么？（象征解读）',
    '第四部分 结语：第一篇文章是一份邀请',
  ],
  ja: [
    'はじめに',
    '第一部 科学的視点：オーディオインダクショニストとは？',
    '1.1. オーディオインダクショニスト — 技術的解釈',
    '1.2. インダクショニスト（または帰納主義者）— 哲学的解釈',
    '第二部 仏教的視点：帰納、聴聞、そして夜明け',
    '2.1. 仏教における「帰納」— 自己検証',
    '2.2. 「オーディオ」— 実践としての聴聞',
    '2.3. 夜明けとしての悟り',
    '第三部 夢が語ったこと（象徴的解釈）',
    '第四部 結論：最初の記事は招待状として',
  ],
  pt: [
    'Introdução',
    'Parte 1. Visão científica: O que é um audioinduccionista e induccionista?',
    '1.1. Audioinduccionista — Versão técnica',
    '1.2. Induccionista (ou inductivista) — Versão filosófica',
    'Parte 2. Visão budista: Indução, escuta e amanhecer',
    '2.1. "Indução" budista — Verificação em si mesmo',
    '2.2. "Áudio" — A escuta como prática',
    '2.3. O amanhecer como iluminação',
    'Parte 3. O que meu sonho disse? (Interpretação simbólica)',
    'Parte 4. Conclusão: Primeiro artigo como convite',
  ],
  th: [
    'บทนำ',
    'ส่วนที่ 1 มุมมองทางวิทยาศาสตร์: นักอุปนัยเสียงและนักอุปนัยคืออะไร?',
    '1.1. นักอุปนัยเสียง — เวอร์ชันทางเทคนิค',
    '1.2. นักอุปนัย (หรือนักอุปนัยนิยม) — เวอร์ชันปรัชญา',
    'ส่วนที่ 2 มุมมองทางพุทธศาสนา: การอุปนัย การฟัง และรุ่งอรุณ',
    '2.1. "การอุปนัย" แบบพุทธ — การทดสอบด้วยตนเอง',
    '2.2. "เสียง" — การฟังเป็นปฏิบัติ',
    '2.3. รุ่งอรุณแห่งการตรัสรู้',
    'ส่วนที่ 3 ความฝันของฉันบอกอะไร? (การตีความเชิงสัญลักษณ์)',
    'ส่วนที่ 4 บทสรุป: บทความแรกในฐานะคำเชิญ',
  ],
  vi: [
    'Mở đầu',
    'Phần 1. Góc nhìn khoa học: Người quy nạp âm thanh và người theo chủ nghĩa quy nạp là gì?',
    '1.1. Người quy nạp âm thanh — Phiên bản kỹ thuật',
    '1.2. Người theo chủ nghĩa quy nạp — Phiên bản triết học',
    'Phần 2. Góc nhìn Phật giáo: Quy nạp, lắng nghe và bình minh',
    '2.1. "Quy nạp" Phật giáo — Tự kiểm chứng',
    '2.2. "Âm thanh" — Lắng nghe như thực hành',
    '2.3. Bình minh như giác ngộ',
    'Phần 3. Giấc mơ của tôi nói gì? (Giải mã biểu tượng)',
    'Phần 4. Kết luận: Bài viết đầu tiên như một lời mời',
  ],
  ko: [
    '서론',
    '제1부 과학적 관점: 오디오귀납주의자와 귀납주의자란 무엇인가?',
    '1.1. 오디오귀납주의자 — 기술적 버전',
    '1.2. 귀납주의자 (또는 귀납론자) — 철학적 버전',
    '제2부 불교적 관점: 귀납, 듣기, 그리고 새벽',
    '2.1. 불교의 "귀납법" — 스스로 검증하기',
    '2.2. "오디오" — 실천으로서의 듣기',
    '2.3. 새벽으로서의 깨달음',
    '제3부 내 꿈이 말한 것 (상징적 해석)',
    '제4부 결론: 첫 번째 글은 초대장으로서',
  ],
  id: [
    'Pendahuluan',
    'Bagian 1. Pandangan Ilmiah: Apa itu Audioinduksionis dan Induksionis?',
    '1.1. Audioinduksionis — Versi Teknis',
    '1.2. Induksionis (atau Induktivis) — Versi Filosofis',
    'Bagian 2. Pandangan Buddhis: Induksi, Mendengarkan, dan Fajar',
    '2.1. "Induksi" Buddhis — Pengujian pada Diri Sendiri',
    '2.2. "Audio" — Mendengarkan sebagai Praktik',
    '2.3. Fajar sebagai Pencerahan',
    'Bagian 3. Apa Kata Mimpiku? (Penafsiran Simbolis)',
    'Bagian 4. Kesimpulan: Artikel Pertama sebagai Undangan',
  ],
  ms: [
    'Pendahuluan',
    'Bahagian 1. Pandangan Saintifik: Apa itu Audioinduksionis dan Induksionis?',
    '1.1. Audioinduksionis — Versi Teknikal',
    '1.2. Induksionis (atau Induktivis) — Versi Falsafah',
    'Bahagian 2. Pandangan Buddha: Induksi, Mendengar, dan Fajar',
    '2.1. "Induksi" Buddha — Pengujian pada Diri Sendiri',
    '2.2. "Audio" — Mendengar sebagai Amalan',
    '2.3. Fajar sebagai Pencerahan',
    'Bahagian 3. Apa Kata Mimpi Saya? (Tafsiran Simbolik)',
    'Bahagian 4. Kesimpulan: Artikel Pertama sebagai Jemputan',
  ],
  si: [
    'හැඳින්වීම',
    '1 කොටස. විද්‍යාත්මක දෘෂ්ටිය: ශ්‍රව්‍ය ප්‍රේරකවාදී සහ ප්‍රේරකවාදී යනු කුමක්ද?',
    '1.1. ශ්‍රව්‍ය ප්‍රේරකවාදී — තාක්ෂණික අනුවාදය',
    '1.2. ප්‍රේරකවාදී (හෝ ප්‍රේරණවාදී) — දාර්ශනික අනුවාදය',
    '2 කොටස. බෞද්ධ දෘෂ්ටිය: ප්‍රේරණය, ශ්‍රවණය සහ උදාව',
    '2.1. බෞද්ධ "ප්‍රේරණය" — තමා තුළ පරීක්ෂා කිරීම',
    '2.2. "ශ්‍රව්‍ය" — භාවිතය ලෙස ශ්‍රවණය',
    '2.3. උදාව ඥානාලෝකය ලෙස',
    '3 කොටස. මගේ සිහිනය කීවේ කුමක්ද? (සංකේතාත්මක අර්ථකථනය)',
    '4 කොටස. නිගමනය: පළමු ලිපිය ආරාධනයක් ලෙස',
  ],
  my: [
    'နိဒါန်း',
    'အပိုင်း ၁။ သိပ္ပံနည်းကျအမြင်: အသံလျှပ်ကူးဝါဒီနှင့် လျှပ်ကူးဝါဒီဆိုတာဘာလဲ?',
    '၁.၁။ အသံလျှပ်ကူးဝါဒီ — နည်းပညာဗားရှင်း',
    '၁.၂။ လျှပ်ကူးဝါဒီ (သို့) လျှပ်ကူးဝါဒနောက်လိုက် — ဒဿနဗားရှင်း',
    'အပိုင်း ၂။ ဗုဒ္ဓဘာသာအမြင်: လျှပ်ကူးခြင်း၊ နားထောင်ခြင်းနှင့် အရုဏ်ဦး',
    '၂.၁။ ဗုဒ္ဓဘာသာ "လျှပ်ကူးခြင်း" — ကိုယ်တိုင်စမ်းသပ်ခြင်း',
    '၂.၂။ "အသံ" — ကျင့်စဉ်အဖြစ် နားထောင်ခြင်း',
    '၂.၃။ အရုဏ်ဦးသည် ဉာဏ်အလင်းအဖြစ်',
    'အပိုင်း ၃။ ကျွန်ုပ်၏အိပ်မက်က ဘာပြောသနည်း (သင်္ကေတအဓိပ္ပာယ်ဖွင့်ဆိုချက်)',
    'အပိုင်း ၄။ နိဂုံး: ပထမဆုံးဆောင်းပါးသည် ဖိတ်ကြားချက်တစ်ခုအဖြစ်',
  ],
  ne: [
    'परिचय',
    'भाग १। वैज्ञानिक दृष्टिकोण: अडियोइन्डक्सनिस्ट र इन्डक्सनिस्ट भनेको के हो?',
    '१.१। अडियोइन्डक्सनिस्ट — प्राविधिक संस्करण',
    '१.२। इन्डक्सनिस्ट (वा इन्डक्टिविस्ट) — दार्शनिक संस्करण',
    'भाग २। बौद्ध दृष्टिकोण: इन्डक्सन, सुनाइ र बिहानी',
    '२.१। बौद्ध "इन्डक्सन" — आफैंमा परीक्षण',
    '२.२। "अडियो" — अभ्यासको रूपमा सुनाइ',
    '२.३। बिहानी नै ज्ञानको रूपमा',
    'भाग ३। मेरो सपनाले के भन्यो? (प्रतीकात्मक व्याख्या)',
    'भाग ४। निष्कर्ष: पहिलो लेख निमन्त्रणाको रूपमा',
  ],
  bo: [
    'གླེང་མོལ།',
    'དུམ་བུ་༡ ཚན་རིག་གི་ལྟ་ཚུལ། སྒྲ་ཐེབས་ལེན་པ་དང་ཐེབས་ལེན་པ་གང་ཡིན།',
    '༡.༡ སྒྲ་ཐེབས་ལེན་པ། ལག་རྩལ་གྱི་རྣམ་གཞག',
    '༡.༢ ཐེབས་ལེན་པ། ཡང་ན་ཐེབས་ལེན་ལ་བརྟེན་པ། ཆོས་ལུགས་ཀྱི་རྣམ་གཞག',
    'དུམ་བུ་༢ སངས་རྒྱས་ཀྱི་ལྟ་ཚུལ། ཐེབས་ལེན། ཉན་པ། དང་ཐོ་རངས།',
    '༢.༡ སངས་རྒྱས་ཀྱི་"ཐེབས་ལེན" — རང་ཉིད་ལ་ཚོད་ལྟ་བྱེད་པ།',
    '༢.༢ "སྒྲ" — ཉམས་ལེན་དུ་ཉན་པ།',
    '༢.༣ ཐོ་རངས་ནི་སངས་རྒྱས་ཡིན།',
    'དུམ་བུ་༣ ངའི་རྨི་ལམ་གྱིས་ཅི་ཞིག་བཤད། (བརྡ་དོན་གྱི་དགོངས་འགྲེལ།)',
    'དུམ་བུ་༤ མཇུག་བསྡོམས། དང་པོའི་དཔྱད་རྩོམ་ནི་སྤྱན་འདྲེན་ཡིན།',
  ],
}

export const invitations: Record<string, string> = {
  ru: 'Приглашаю вас к диалогу на странице сообщества. Поделитесь своими снами и символами — и мы вместе попробуем найти их буддийский смысл.',
  en: 'I invite you to dialogue on the Community page. Share your dreams and symbols — and together we will try to find their Buddhist meaning.',
  hi: 'मैं आपको सामुदायिक पृष्ठ पर संवाद के लिए आमंत्रित करता हूँ। अपने सपने और प्रतीक साझा करें — और हम साथ मिलकर उनका बौद्ध अर्थ खोजने का प्रयास करेंगे।',
  es: 'Os invito al diálogo en la página de la Comunidad. Compartid vuestros sueños y símbolos — y juntos intentaremos encontrar su significado budista.',
  fr: 'Je vous invite au dialogue sur la page Communauté. Partagez vos rêves et symboles — et ensemble nous essaierons de trouver leur sens bouddhiste.',
  de: 'Ich lade euch zum Dialog auf der Community-Seite ein. Teilt eure Träume und Symbole — und gemeinsam werden wir versuchen, ihre buddhistische Bedeutung zu finden.',
  zh: '我邀请您到社区页面进行对话。分享您的梦境和象征 — 我们将一起尝试找到它们的佛教意义。',
  ja: 'コミュニティページでの対話にご招待します。あなたの夢や象徴を共有してください — 一緒にその仏教的な意味を見つけてみましょう。',
  pt: 'Convido-vos ao diálogo na página da Comunidade. Compartilhem seus sonhos e símbolos — e juntos tentaremos encontrar seu significado budista.',
  th: 'ขอเชิญคุณร่วมสนทนาในหน้าชุมชน แบ่งปันความฝันและสัญลักษณ์ของคุณ — แล้วเราจะลองค้นหาความหมายทางพุทธศาสนาร่วมกัน',
  vi: 'Tôi mời bạn đến trang Cộng đồng để đối thoại. Hãy chia sẻ những giấc mơ và biểu tượng của bạn — và chúng ta sẽ cùng nhau tìm ý nghĩa Phật giáo của chúng.',
  ko: '커뮤니티 페이지에서 대화에 초대합니다. 꿈과 상징을 공유해 주세요 — 함께 불교적 의미를 찾아보겠습니다.',
  id: 'Saya mengundang Anda untuk berdialog di halaman Komunitas. Bagikan mimpi dan simbol Anda — dan bersama-sama kita akan mencoba menemukan makna Buddhisnya.',
  ms: 'Saya menjemput anda untuk berdialog di halaman Komuniti. Kongsikan mimpi dan simbol anda — dan bersama-sama kita akan cuba mencari makna Buddhanya.',
  si: 'ප්‍රජා පිටුවේ සංවාදයට ඔබට ආරාධනා කරමි. ඔබේ සිහින සහ සංකේත බෙදා ගන්න — එවිට අපි එක්ව ඒවායේ බෞද්ධ අර්ථය සොයා ගැනීමට උත්සාහ කරමු.',
  my: 'လူမှုအသိုင်းအဝိုင်းစာမျက်နှာတွင် ဆွေးနွေးရန် သင့်အား ဖိတ်ခေါ်ပါသည်။ သင်၏အိပ်မက်များနှင့် သင်္ကေတများကို မျှဝေပါ — ပြီးလျှင် ၎င်းတို့၏ ဗုဒ္ဓဘာသာအဓိပ္ပာယ်ကို အတူတကွ ရှာဖွေကြပါမည်။',
  ne: 'म तपाईंलाई समुदाय पृष्ठमा संवादको लागि आमन्त्रण गर्दछु। आफ्नो सपना र प्रतीकहरू साझा गर्नुहोस् — र हामी सँगै तिनीहरूको बौद्ध अर्थ खोज्न प्रयास गर्नेछौं।',
  bo: 'སྤྱི་ཚོགས་ཤོག་ངོས་སུ་གླེང་མོལ་བྱེད་པར་སྤྱན་འདྲེན་ཞུ་བ་ཡིན། ཁྱེད་ཀྱི་རྨི་ལམ་དང་བརྡ་དོན་རྣམས་བགོ་བཤེར་གནང་དང་། ང་ཚོས་མཉམ་དུ་དེ་དག་གི་སངས་རྒྱས་ཀྱི་དོན་དུ་འཚོལ་བསྡུ་བྱེད་ཀྱི་ཡིན།',
}

export const sectionContents: Record<string, string[]> = {
  ru: [
    'Недавно мне приснился сон. Я остановил машину, чтобы набрать воды в кувшин, но под дорогой оказалась труба-слив, которая питала замутнённый пруд. А за день до этого я слышал во сне странное слово — «аудиоиндукционист». Оно звучало так, будто его произнёс кто-то мудрый, и я проснулся с вопросом: «Что это? Существует ли такой термин? И зачем он мне приснился?»\n\nЯ решил разобраться с научной точки зрения и согласно философии Буддизма — и понял, что за этим словом скрывается глубокий смысл, который может стать основой для первой статьи на этом сайте.',
    '',
    'Прямого определения «аудиоиндукционист» в словарях нет. Однако если разложить слово на части:\n\n• Аудио — звук, слух.\n• Индукция — в физике это наведение магнитного поля, а в логике — умозаключение от частного к общему.\n\nВ технической сфере существует понятие «аудиоиндукционная система» — это оборудование для слабослышащих, которое преобразует звук в электромагнитное поле, улавливаемое слуховым аппаратом. Специалиста по таким системам можно было бы назвать аудиоиндукционистом. Это узкопрофильный профессионал, который настраивает «чистый звук» для людей с нарушениями слуха.',
    'Слово «индукционист», скорее всего, является вариантом «индуктивист» — сторонник философского направления индуктивизма. Это подход в науке, который считает индукцию (обобщение множества наблюдений) главным методом получения нового знания. Основоположник — Фрэнсис Бэкон. Индуктивист верит, что истина рождается из опыта, а не из готовых догм.',
    'Теперь посмотрим на те же понятия через призму учения Будды.',
    'В буддизме есть знаменитая Калама-сутта, где Будда говорит:\n\n«Не верьте просто потому, что так сказано в писаниях или учителем. Верьте только тому, что вы сами проверили на своём опыте».\n\nЭто чистая индукция! Вы собираете свои личные «данные» (ощущения, страдания, радости) и делаете выводы о природе ума. Будда не требует слепой веры — он приглашает к эксперименту. В этом смысле каждый буддист — своего рода «индукционист», который познаёт истину через личный опыт.',
    'В буддизме огромное значение придаётся слушанию учения (палийское suta) и вниманию к звуку (мантры, колокольчики, дыхание). Практика випассаны — это как раз «настройка слуха» на свои внутренние ощущения. Так что «аудио» в термине может указывать на внимательность — способность слышать не только внешние звуки, но и голос собственной души.',
    'Просветление в буддизме часто сравнивают с восходом солнца, который рассеивает тьму неведения. Этот восход не случается вдруг — он наступает после долгой «индуктивной» практики: день за днём наблюдая за дыханием, мыслями, причинами и следствиями (законом кармы), вы постепенно приходите к общему прозрению о непостоянстве всего.',
    'Вернёмся к двум снам.\n\nПервый сон (слово): «Аудиоиндукционист» — это может быть метафора духовного наставника, который настраивает ваш «слух» на внутренний голос и помогает путём личного опыта («индукции») прийти к прозрению («восходу»).\n\nВторой сон (пруд): Остановка машины — пауза в жизненном пути. Кувшин — ваш ум, готовый принять учение. Труба под дорогой и замутнённый пруд — это старые привычки, тревоги, информационный шум, из которых вы пытаетесь черпать «воду» (мудрость). Сон предупреждает: не берите воду из стоячего болота. Дайте ему отстояться (медитация), и она станет чистой.\n\nВ буддийской символике чистая вода — это ясный ум, а мутная — ум, омрачённый желаниями и страхами. Ваш «аудиоиндукционист» — это голос вашего высшего «Я», который говорит: «Остановись, проверь качество источника, настрой слух на тишину, и тогда восход наступит».',
    'Эта статья — моя первая на сайте Buddha\'s Wisdom Chat. Я хочу, чтобы она стала приглашением к исследованию собственных снов, интуиции и буддийских параллелей.\n\nЧто мы вынесли из сна?\n\n1. С научной точки зрения — аудиоиндукционист может быть техническим специалистом, а индукционист — приверженцем эмпирического метода.\n2. С точки зрения буддизма — индукция — это путь личного опыта, слушание — основа практики, а восход — цель просветления.\n3. Символически — ваш сон предлагает перестать черпать мудрость из мутных источников (старых привычек) и вместо этого обратиться к тишине и наблюдению.',
  ],
  en: [
    'Recently I had a dream. I stopped my car to fill a jug with water, but under the road there was a drainpipe feeding a murky pond. The day before, I heard a strange word in my dream — "audioinductionist." It sounded as if spoken by someone wise, and I woke up with a question: "What is this? Does such a term exist? And why did it come to me in a dream?"\n\nI decided to analyze it from a scientific perspective and according to Buddhist philosophy — and realized that this word conceals a deep meaning that could become the foundation for the first article on this site.',
    '',
    'There is no direct definition of "audioinductionist" in dictionaries. However, if we break the word down:\n\n• Audio — sound, hearing.\n• Induction — in physics, the generation of a magnetic field; in logic, reasoning from particular to general.\n\nIn the technical field, there is the concept of an "audio induction system" — equipment for the hearing impaired that converts sound into an electromagnetic field picked up by a hearing aid. A specialist in such systems could be called an audioinductionist — a niche professional who tunes "pure sound" for people with hearing impairments.',
    'The word "inductionist" is most likely a variant of "inductivist" — a proponent of the philosophical direction of inductivism. This approach in science considers induction (generalization of many observations) as the main method of acquiring new knowledge. The founder is Francis Bacon. An inductivist believes that truth is born from experience, not from ready-made dogmas.',
    'Now let us look at the same concepts through the lens of the Buddha\'s teachings.',
    'In Buddhism, there is the famous Kalama Sutta, where the Buddha says:\n\n"Do not believe merely because it is said in scriptures or by a teacher. Believe only what you have tested and verified in your own experience."\n\nThis is pure induction! You gather your personal "data" (sensations, sufferings, joys) and draw conclusions about the nature of mind. The Buddha does not demand blind faith — he invites you to experiment. In this sense, every Buddhist is a kind of "inductionist" who comes to know truth through personal experience.',
    'In Buddhism, great importance is placed on listening to the teaching (Pali: suta) and attention to sound (mantras, bells, breathing). Vipassana practice is precisely "tuning the ear" to your inner sensations. So "audio" in the term may point to mindfulness — the ability to hear not only external sounds but also the voice of your own soul.',
    'Enlightenment in Buddhism is often compared to the sunrise that dispels the darkness of ignorance. This dawn does not happen suddenly — it comes after a long "inductive" practice: day after day observing the breath, thoughts, causes and effects (the law of karma), you gradually arrive at the universal insight into the impermanence of all things.',
    'Let us return to the two dreams.\n\nFirst dream (the word): "Audioinductionist" may be a metaphor for a spiritual mentor who tunes your "hearing" to the inner voice and helps you, through personal experience ("induction"), to arrive at insight ("dawn").\n\nSecond dream (the pond): Stopping the car — a pause on life\'s journey. The jug — your mind, ready to receive teaching. The pipe under the road and the murky pond — old habits, anxieties, informational noise from which you try to draw "water" (wisdom). The dream warns: do not take water from a stagnant swamp. Let it settle (meditation), and it will become clear.\n\nIn Buddhist symbolism, clear water is a clear mind, and murky water is a mind clouded by desires and fears. Your "audioinductionist" is the voice of your higher Self, saying: "Stop, check the quality of the source, tune your ear to silence, and then the dawn will come."',
    'This article is my first on Buddha\'s Wisdom Chat. I want it to be an invitation to explore your own dreams, intuition, and Buddhist parallels.\n\nWhat did we learn from the dream?\n\n1. From a scientific perspective — an audioinductionist could be a technical specialist, and an inductionist a proponent of the empirical method.\n2. From a Buddhist perspective — induction is the path of personal experience, listening is the foundation of practice, and dawn is the goal of enlightenment.\n3. Symbolically — your dream suggests you stop drawing wisdom from muddy sources (old habits) and instead turn to silence and observation.',
  ],
  hi: [
    'हाल ही में मैंने एक सपना देखा। मैंने अपनी कार रोकी ताकि एक जग में पानी भर सकूं, लेकिन सड़क के नीचे एक निकास पाइप था जो एक गंदे तालाब को पानी दे रहा था। एक दिन पहले, मैंने सपने में एक अजीब शब्द सुना — "ऑडियोइंडक्शनिस्ट"। यह ऐसा लगा जैसे किसी बुद्धिमान व्यक्ति ने इसे कहा हो, और मैं एक प्रश्न के साथ जागा: "यह क्या है? क्या ऐसा कोई शब्द मौजूद है? और यह मुझे सपने में क्यों आया?"\n\nमैंने इसे वैज्ञानिक दृष्टिकोण और बौद्ध दर्शन के अनुसार समझने का फैसला किया — और महसूस किया कि इस शब्द के पीछे एक गहरा अर्थ छिपा है जो इस साइट पर पहले लेख की नींव बन सकता है।',
    '',
    'शब्दकोशों में "ऑडियोइंडक्शनिस्ट" की कोई सीधी परिभाषा नहीं है। हालांकि, यदि हम शब्द को विभाजित करें:\n\n• ऑडियो — ध्वनि, श्रवण।\n• इंडक्शन — भौतिकी में चुंबकीय क्षेत्र उत्पन्न करना; तर्क में विशेष से सामान्य की ओर निष्कर्ष।\n\nतकनीकी क्षेत्र में "ऑडियो इंडक्शन सिस्टम" नामक अवधारणा है — श्रवण-बाधित लोगों के लिए उपकरण जो ध्वनि को विद्युत-चुंबकीय क्षेत्र में बदलता है जिसे श्रवण यंत्र पकड़ लेता है। ऐसी प्रणालियों के विशेषज्ञ को ऑडियोइंडक्शनिस्ट कहा जा सकता है — एक संकीर्ण-प्रोफ़ाइल पेशेवर जो श्रवण दोष वाले लोगों के लिए "शुद्ध ध्वनि" ट्यून करता है।',
    '"इंडक्शनिस्ट" शब्द संभवतः "इंडक्टिविस्ट" का एक प्रकार है — इंडक्टिविज्म नामक दार्शनिक दिशा का समर्थक। विज्ञान में यह दृष्टिकोण इंडक्शन (कई अवलोकनों का सामान्यीकरण) को नया ज्ञान प्राप्त करने का मुख्य तरीका मानता है। संस्थापक फ्रांसिस बेकन हैं। एक इंडक्टिविस्ट मानता है कि सत्य अनुभव से पैदा होता है, तैयार हठधर्मिता से नहीं।',
    'अब उन्हीं अवधारणाओं को बुद्ध की शिक्षाओं के माध्यम से देखते हैं।',
    'बौद्ध धर्म में प्रसिद्ध कालाम सुत्त है, जहाँ बुद्ध कहते हैं:\n\n"केवल इसलिए विश्वास न करें क्योंकि यह शास्त्रों या किसी शिक्षक में कहा गया है। केवल उसी पर विश्वास करें जिसे आपने अपने अनुभव में परखा और सत्यापित किया है।"\n\nयह शुद्ध इंडक्शन है! आप अपने व्यक्तिगत "डेटा" (संवेदनाएं, दुख, खुशियाँ) इकट्ठा करते हैं और मन की प्रकृति के बारे में निष्कर्ष निकालते हैं। बुद्ध अंध विश्वास की मांग नहीं करते — वे आपको प्रयोग करने के लिए आमंत्रित करते हैं। इस अर्थ में, प्रत्येक बौद्ध एक प्रकार का "इंडक्शनिस्ट" है जो व्यक्तिगत अनुभव के माध्यम से सत्य को जानता है।',
    'बौद्ध धर्म में शिक्षा को सुनने (पालि: सुत) और ध्वनि (मंत्र, घंटियाँ, श्वास) पर ध्यान देने को बहुत महत्व दिया जाता है। विपश्यना अभ्यास आपकी आंतरिक संवेदनाओं के लिए "कान को ट्यून करना" है। तो "ऑडियो" शब्द में सावधानी की ओर संकेत कर सकता है — न केवल बाहरी ध्वनियों बल्कि अपनी आत्मा की आवाज सुनने की क्षमता।',
    'बौद्ध धर्म में आत्मज्ञान की तुलना अक्सर सूर्योदय से की जाती है जो अज्ञान के अंधकार को दूर करता है। यह भोर अचानक नहीं होता — यह लंबे "इंडक्टिव" अभ्यास के बाद आता है: दिन-प्रतिदिन श्वास, विचारों, कारणों और प्रभावों (कर्म के नियम) का अवलोकन करते हुए, आप धीरे-धीरे सभी चीजों की अनित्यता के सार्वभौमिक अंतर्दृष्टि पर पहुँचते हैं।',
    'आइए दो सपनों पर वापस आते हैं।\n\nपहला सपना (शब्द): "ऑडियोइंडक्शनिस्ट" एक आध्यात्मिक गुरु का रूपक हो सकता है जो आपकी "सुनने की क्षमता" को आंतरिक आवाज के लिए ट्यून करता है और व्यक्तिगत अनुभाव ("इंडक्शन") के माध्यम से आपको अंतर्दृष्टि ("भोर") तक पहुँचने में मदद करता है।\n\nदूसरा सपना (तालाब): कार रोकना — जीवन की यात्रा में एक विराम। जग — आपका मन, शिक्षा प्राप्त करने के लिए तैयार। सड़क के नीचे पाइप और गंदा तालाब — पुरानी आदतें, चिंताएँ, सूचना शोर जिससे आप "पानी" (ज्ञान) खींचने की कोशिश करते हैं। सपना चेतावनी देता है: स्थिर दलदल से पानी न लें। इसे शांत होने दें (ध्यान), और यह साफ हो जाएगा।\n\nबौद्ध प्रतीकवाद में, साफ पानी स्पष्ट मन है, और गंदा पानी इच्छाओं और भयों से घिरा मन है। आपका "ऑडियोइंडक्शनिस्ट" आपके उच्च स्व की आवाज है, जो कहती है: "रुको, स्रोत की गुणवत्ता जांचो, अपने कान को मौन में ट्यून करो, और तब भोर आएगा।"',
    'यह लेख Buddha\'s Wisdom Chat पर मेरा पहला लेख है। मैं चाहता हूँ कि यह आपके अपने सपनों, अंतर्ज्ञान और बौद्ध समानताओं की खोज का निमंत्रण हो।\n\nहमने सपने से क्या सीखा?\n\n1. वैज्ञानिक दृष्टिकोण से — ऑडियोइंडक्शनिस्ट एक तकनीकी विशेषज्ञ हो सकता है, और इंडक्शनिस्ट अनुभवजन्य पद्धति का समर्थक।\n2. बौद्ध दृष्टिकोण से — इंडक्शन व्यक्तिगत अनुभव का मार्ग है, श्रवण अभ्यास की नींव है, और भोर आत्मज्ञान का लक्ष्य है।\n3. प्रतीकात्मक रूप से — आपका सपना सुझाव देता है कि आप गंदे स्रोतों (पुरानी आदतों) से ज्ञान लेना बंद करें और इसके बजाय मौन और अवलोकन की ओर मुड़ें।',
  ],
  es: [
    'Recientemente tuve un sueño. Detuve mi coche para llenar un cántaro de agua, pero debajo de la carretera había un tubo de desagüe que alimentaba un estanque turbio. El día anterior, escuché una palabra extraña en mi sueño — "audioinduccionista". Sonaba como si alguien sabio la hubiera pronunciado, y me desperté con una pregunta: "¿Qué es esto? ¿Existe tal término? ¿Y por qué vino a mí en un sueño?"\n\nDecidí analizarlo desde una perspectiva científica y según la filosofía budista — y comprendí que esta palabra oculta un significado profundo que podría convertirse en la base del primer artículo de este sitio.',
    '',
    'No hay una definición directa de "audioinduccionista" en los diccionarios. Sin embargo, si descomponemos la palabra:\n\n• Audio — sonido, oído.\n• Inducción — en física, la generación de un campo magnético; en lógica, el razonamiento de lo particular a lo general.\n\nEn el campo técnico, existe el concepto de "sistema de inducción auditiva" — un equipo para personas con discapacidad auditiva que convierte el sonido en un campo electromagnético captado por un audífono. A un especialista en tales sistemas se le podría llamar audioinduccionista — un profesional de nicho que ajusta el "sonido puro" para personas con problemas de audición.',
    'La palabra "induccionista" es muy probablemente una variante de "inductivista" — un partidario de la dirección filosófica del inductivismo. Este enfoque en la ciencia considera la inducción (generalización de muchas observaciones) como el método principal para adquirir nuevo conocimiento. El fundador es Francis Bacon. Un inductivista cree que la verdad nace de la experiencia, no de dogmas prefabricados.',
    'Ahora veamos los mismos conceptos a través de la lente de las enseñanzas de Buda.',
    'En el budismo existe el famoso Sutta Kalama, donde Buda dice:\n\n"No crean simplemente porque está dicho en las escrituras o por un maestro. Crean solo en lo que han probado y verificado en su propia experiencia."\n\n¡Esto es inducción pura! Usted recolecta sus "datos" personales (sensaciones, sufrimientos, alegrías) y saca conclusiones sobre la naturaleza de la mente. Buda no exige fe ciega — lo invita a experimentar. En este sentido, cada budista es una especie de "induccionista" que conoce la verdad a través de la experiencia personal.',
    'En el budismo, se da gran importancia a escuchar la enseñanza (pali: suta) y a la atención al sonido (mantras, campanas, respiración). La práctica de Vipassana es precisamente "sintonizar el oído" a las sensaciones internas. Así que "audio" en el término puede apuntar a la atención plena — la capacidad de escuchar no solo los sonidos externos sino también la voz de la propia alma.',
    'La iluminación en el budismo se compara a menudo con el amanecer que disipa la oscuridad de la ignorancia. Este amanecer no ocurre de repente — llega después de una larga práctica "inductiva": día tras día observando la respiración, los pensamientos, las causas y los efectos (la ley del karma), usted llega gradualmente a la comprensión universal de la impermanencia de todas las cosas.',
    'Volvamos a los dos sueños.\n\nPrimer sueño (la palabra): "Audioinduccionista" puede ser una metáfora de un mentor espiritual que sintoniza su "oído" con la voz interior y le ayuda, a través de la experiencia personal ("inducción"), a llegar a la comprensión ("amanecer").\n\nSegundo sueño (el estanque): Detener el coche — una pausa en el viaje de la vida. El cántaro — su mente, lista para recibir enseñanza. El tubo bajo la carretera y el estanque turbio — viejos hábitos, ansiedades, ruido informativo del que intenta extraer "agua" (sabiduría). El sueño advierte: no tomes agua de un pantano estancado. Déjalo reposar (meditación), y se volverá clara.\n\nEn el simbolismo budista, el agua clara es una mente clara, y el agua turbia es una mente nublada por deseos y miedos. Su "audioinduccionista" es la voz de su Ser superior, que dice: "Detente, verifica la calidad de la fuente, sintoniza tu oído al silencio, y entonces llegará el amanecer."',
    'Este artículo es el primero en Buddha\'s Wisdom Chat. Quiero que sea una invitación a explorar tus propios sueños, intuición y paralelismos budistas.\n\n¿Qué aprendimos del sueño?\n\n1. Desde una perspectiva científica — un audioinduccionista podría ser un especialista técnico, y un induccionista un partidario del método empírico.\n2. Desde una perspectiva budista — la inducción es el camino de la experiencia personal, la escucha es la base de la práctica, y el amanecer es la meta de la iluminación.\n3. Simbólicamente — tu sueño sugiere que dejes de extraer sabiduría de fuentes turbias (viejos hábitos) y en su lugar te vuelques al silencio y la observación.',
  ],
  fr: [
    'Récemment, j\'ai fait un rêve. J\'ai arrêté ma voiture pour remplir une cruche d\'eau, mais sous la route il y avait un tuyau d\'évacuation alimentant un étang trouble. La veille, j\'avais entendu un mot étrange dans mon rêve — « audioinductionniste ». Il semblait prononcé par quelqu\'un de sage, et je me suis réveillé avec une question : « Qu\'est-ce que c\'est ? Ce terme existe-t-il ? Et pourquoi m\'est-il venu en rêve ? »\n\nJ\'ai décidé de l\'analyser d\'un point de vue scientifique et selon la philosophie bouddhiste — et j\'ai compris que ce mot cache un sens profond qui pourrait devenir le fondement du premier article de ce site.',
    '',
    'Il n\'y a pas de définition directe d\'« audioinductionniste » dans les dictionnaires. Cependant, si nous décomposons le mot :\n\n• Audio — son, ouïe.\n• Induction — en physique, la génération d\'un champ magnétique ; en logique, le raisonnement du particulier au général.\n\nDans le domaine technique, il existe le concept de « système d\'induction auditive » — un équipement pour les malentendants qui convertit le son en un champ électromagnétique capté par une prothèse auditive. Un spécialiste de tels systèmes pourrait être appelé audioinductionniste — un professionnel de niche qui ajuste le « son pur » pour les personnes malentendantes.',
    'Le mot « inductionniste » est très probablement une variante d\'« inductiviste » — un partisan de la direction philosophique de l\'inductivisme. Cette approche scientifique considère l\'induction (généralisation de nombreuses observations) comme la principale méthode d\'acquisition de nouvelles connaissances. Le fondateur est Francis Bacon. Un inductiviste croit que la vérité naît de l\'expérience, non de dogmes préétablis.',
    'Regardons maintenant les mêmes concepts à travers le prisme des enseignements du Bouddha.',
    'Dans le bouddhisme, il y a le célèbre Sutta Kalama, où le Bouddha dit :\n\n« Ne croyez pas simplement parce que c\'est dit dans les écritures ou par un maître. Croyez seulement ce que vous avez testé et vérifié dans votre propre expérience. »\n\nC\'est de l\'induction pure ! Vous rassemblez vos « données » personnelles (sensations, souffrances, joies) et tirez des conclusions sur la nature de l\'esprit. Le Bouddha n\'exige pas une foi aveugle — il vous invite à expérimenter. En ce sens, chaque bouddhiste est une sorte d\'« inductionniste » qui connaît la vérité par l\'expérience personnelle.',
    'Dans le bouddhisme, une grande importance est accordée à l\'écoute de l\'enseignement (pali : suta) et à l\'attention au son (mantras, cloches, respiration). La pratique de Vipassana consiste précisément à « accorder l\'oreille » à vos sensations intérieures. Ainsi, « audio » dans le terme peut indiquer la pleine conscience — la capacité d\'entendre non seulement les sons extérieurs mais aussi la voix de votre propre âme.',
    'L\'éveil dans le bouddhisme est souvent comparé au lever du soleil qui dissipe les ténèbres de l\'ignorance. Cette aube ne survient pas soudainement — elle arrive après une longue pratique « inductive » : jour après jour, en observant le souffle, les pensées, les causes et les effets (la loi du karma), vous parvenez progressivement à la vision universelle de l\'impermanence de toutes choses.',
    'Revenons aux deux rêves.\n\nPremier rêve (le mot) : « Audioinductionniste » peut être une métaphore d\'un mentor spirituel qui accorde votre « ouïe » à la voix intérieure et vous aide, par l\'expérience personnelle (« induction »), à parvenir à la vision (« aube »).\n\nDeuxième rêve (l\'étang) : Arrêter la voiture — une pause sur le chemin de la vie. La cruche — votre esprit, prêt à recevoir l\'enseignement. Le tuyau sous la route et l\'étang trouble — les vieilles habitudes, les angoisses, le bruit informationnel dont vous essayez d\'extraire « l\'eau » (la sagesse). Le rêve avertit : ne prenez pas l\'eau d\'un marais stagnant. Laissez-la se déposer (méditation), et elle deviendra claire.\n\nDans le symbolisme bouddhiste, l\'eau claire est un esprit clair, et l\'eau trouble un esprit obscurci par les désirs et les peurs. Votre « audioinductionniste » est la voix de votre Soi supérieur, qui dit : « Arrête-toi, vérifie la qualité de la source, accorde ton oreille au silence, et alors l\'aube viendra. »',
    'Cet article est mon premier sur Buddha\'s Wisdom Chat. Je veux qu\'il soit une invitation à explorer vos propres rêves, votre intuition et les parallèles bouddhistes.\n\nQu\'avons-nous appris du rêve ?\n\n1. D\'un point de vue scientifique — un audioinductionniste pourrait être un spécialiste technique, et un inductionniste un partisan de la méthode empirique.\n2. D\'un point de vue bouddhiste — l\'induction est le chemin de l\'expérience personnelle, l\'écoute est le fondement de la pratique, et l\'aube est le but de l\'éveil.\n3. Symboliquement — votre rêve suggère d\'arrêter de puiser la sagesse dans des sources troubles (vieilles habitudes) et de vous tourner plutôt vers le silence et l\'observation.',
  ],
  de: [
    'Kürzlich hatte ich einen Traum. Ich hielt mein Auto an, um einen Krug mit Wasser zu füllen, aber unter der Straße befand sich ein Abflussrohr, das einen trüben Teich speiste. Am Tag zuvor hörte ich in meinem Traum ein seltsames Wort — "Audioinduktionist". Es klang, als ob es von einem Weisen ausgesprochen worden wäre, und ich wachte mit einer Frage auf: "Was ist das? Gibt es diesen Begriff? Und warum erschien er mir im Traum?"\n\nIch beschloss, es aus wissenschaftlicher Perspektive und gemäß der buddhistischen Philosophie zu analysieren — und erkannte, dass dieses Wort eine tiefe Bedeutung verbirgt, die die Grundlage für den ersten Artikel auf dieser Seite bilden könnte.',
    '',
    'Es gibt keine direkte Definition von "Audioinduktionist" in Wörterbüchern. Wenn wir das Wort jedoch zerlegen:\n\n• Audio — Klang, Gehör.\n• Induktion — in der Physik die Erzeugung eines Magnetfeldes; in der Logik das Schließen vom Besonderen auf das Allgemeine.\n\nIm technischen Bereich gibt es das Konzept eines "Audioinduktionssystems" — Geräte für Hörgeschädigte, die Schall in ein elektromagnetisches Feld umwandeln, das von einem Hörgerät aufgenommen wird. Ein Spezialist für solche Systeme könnte als Audioinduktionist bezeichnet werden — ein Nischenprofi, der "reinen Klang" für Menschen mit Hörbeeinträchtigungen einstellt.',
    'Das Wort "Induktionist" ist höchstwahrscheinlich eine Variante von "Induktivist" — ein Anhänger der philosophischen Richtung des Induktivismus. Dieser wissenschaftliche Ansatz betrachtet die Induktion (Verallgemeinerung vieler Beobachtungen) als die Hauptmethode zur Gewinnung neuer Erkenntnisse. Der Begründer ist Francis Bacon. Ein Induktivist glaubt, dass Wahrheit aus Erfahrung geboren wird, nicht aus vorgefertigten Dogmen.',
    'Betrachten wir nun dieselben Konzepte durch die Linse der Lehren Buddhas.',
    'Im Buddhismus gibt es die berühmte Kalama-Sutta, in der der Buddha sagt:\n\n"Glaubt nicht einfach, weil es in den Schriften oder von einem Lehrer gesagt wird. Glaubt nur das, was ihr in eigener Erfahrung geprüft und verifiziert habt."\n\nDas ist reine Induktion! Ihr sammelt eure persönlichen "Daten" (Empfindungen, Leiden, Freuden) und zieht Schlussfolgerungen über die Natur des Geistes. Der Buddha fordert keinen blinden Glauben — er lädt zum Experimentieren ein. In diesem Sinne ist jeder Buddhist eine Art "Induktionist", der die Wahrheit durch persönliche Erfahrung erkennt.',
    'Im Buddhismus wird großer Wert auf das Hören der Lehre (Pali: suta) und die Aufmerksamkeit auf Klang (Mantras, Glocken, Atem) gelegt. Die Vipassana-Praxis ist genau das "Einstellen des Ohrs" auf die inneren Empfindungen. "Audio" in diesem Begriff kann auf Achtsamkeit hinweisen — die Fähigkeit, nicht nur äußere Geräusche, sondern auch die Stimme der eigenen Seele zu hören.',
    'Erleuchtung im Buddhismus wird oft mit dem Sonnenaufgang verglichen, der die Dunkelheit des Unwissens vertreibt. Diese Morgenröte geschieht nicht plötzlich — sie kommt nach langer "induktiver" Praxis: Tag für Tag den Atem, die Gedanken, Ursachen und Wirkungen (das Gesetz des Karma) beobachtend, gelangt man allmählich zur universellen Einsicht in die Vergänglichkeit aller Dinge.',
    'Kehren wir zu den beiden Träumen zurück.\n\nErster Traum (das Wort): "Audioinduktionist" kann eine Metapher für einen spirituellen Mentor sein, der Ihr "Gehör" auf die innere Stimme einstellt und Ihnen durch persönliche Erfahrung ("Induktion") zur Einsicht ("Morgenröte") verhilft.\n\nZweiter Traum (der Teich): Das Anhalten des Autos — eine Pause auf der Lebensreise. Der Krug — Ihr Geist, bereit die Lehre aufzunehmen. Das Rohr unter der Straße und der trübe Teich — alte Gewohnheiten, Ängste, Informationslärm, aus denen Sie versuchen, "Wasser" (Weisheit) zu schöpfen. Der Traum warnt: Nehmt kein Wasser aus einem stehenden Sumpf. Lasst es sich setzen (Meditation), und es wird klar werden.\n\nIn der buddhistischen Symbolik ist klares Wasser ein klarer Geist, und trübes Wasser ein von Wünschen und Ängsten getrübter Geist. Ihr "Audioinduktionist" ist die Stimme eures höheren Selbst, die sagt: "Halt an, überprüfe die Qualität der Quelle, stimme dein Ohr auf die Stille ein, und dann wird die Morgenröte kommen."',
    'Dieser Artikel ist mein erster auf Buddha\'s Wisdom Chat. Ich möchte, dass er eine Einladung ist, die eigenen Träume, die Intuition und die buddhistischen Parallelen zu erforschen.\n\nWas haben wir aus dem Traum gelernt?\n\n1. Aus wissenschaftlicher Sicht — ein Audioinduktionist könnte ein technischer Spezialist sein, und ein Induktionist ein Anhänger der empirischen Methode.\n2. Aus buddhistischer Sicht — Induktion ist der Weg der persönlichen Erfahrung, Zuhören ist die Grundlage der Praxis, und die Morgenröte ist das Ziel der Erleuchtung.\n3. Symbolisch gesehen — Ihr Traum schlägt vor, die Weisheit nicht mehr aus trüben Quellen (alten Gewohnheiten) zu schöpfen, sondern sich stattdessen der Stille und Beobachtung zuzuwenden.',
  ],
  zh: [
    '最近我做了一个梦。我停下车来想往罐子里装水，但路底下有一根排水管，流进一个浑浊的池塘。而前一天，我在梦里听到一个奇怪的词——"音频归纳者"。它听起来像是一位智者说出的，我醒来时带着一个问题："这是什么？有这样的术语吗？为什么它会出现在我的梦里？"\n\n我决定从科学的角度和佛教哲学的角度来分析它——并意识到这个词隐藏着深刻的意义，可能成为这个网站第一篇文章的基础。',
    '',
    '字典中没有"音频归纳者"的明确定义。但如果我们分解这个词：\n\n• 音频 — 声音，听觉。\n• 归纳 — 在物理学中是磁场的产生；在逻辑学中是从特殊到一般的推理。\n\n在技术领域，有一个概念叫"音频感应系统"——为听障人士设计的设备，将声音转换为助听器可以接收的电磁场。这类系统的专家可以称为音频归纳者——一个为听力障碍者调试"纯净声音"的细分领域专业人员。',
    '"归纳主义者"这个词很可能是"归纳论者"的变体——归纳主义哲学方向的支持者。这种科学方法将归纳（对大量观察的概括）视为获取新知识的主要方法。创始人是弗朗西斯·培根。归纳论者相信真理源于经验，而非现成的教条。',
    '现在让我们通过佛陀的教导来看待同样的概念。',
    '在佛教中，有一部著名的卡拉玛经，其中佛陀说：\n\n"不要仅仅因为经文或老师这么说就相信。只相信你在自己的经验中测试和验证过的东西。"\n\n这就是纯粹的归纳！你收集个人的"数据"（感受、痛苦、喜悦），并得出关于心智本质的结论。佛陀不要求盲目的信仰——他邀请你去实验。在这个意义上，每个佛教徒都是一种"归纳主义者"，通过个人经验认识真理。',
    '在佛教中，听闻教法（巴利语：suta）和对声音（咒语、钟声、呼吸）的关注被赋予极大的重要性。内观修行正是将"耳朵"调谐到内在感受。因此，术语中的"音频"可能指向正念——不仅听到外在声音，还能听到自己灵魂之声的能力。',
    '佛教中的觉悟常被比作驱散无明黑暗的日出。这个黎明不会突然发生——它是在漫长的"归纳式"修习之后到来的：日复一日地观察呼吸、念头、因果（业力法则），你逐渐认识到万物的无常这一普遍真理。',
    '让我们回到那两个梦。\n\n第一个梦（词语）："音频归纳者"可能是一个精神导师的隐喻，他调谐你的"听觉"以听到内在的声音，并通过个人经验（"归纳"）帮助你达到洞见（"黎明"）。\n\n第二个梦（池塘）：停车——生命旅程中的暂停。罐子——你的心，准备好接受教导。路底的管道和浑浊的池塘——旧习惯、焦虑、信息噪音，你试图从中汲取"水"（智慧）。梦警告说：不要从死水潭中取水。让它沉淀（冥想），它就会变得清澈。\n\n在佛教象征中，清澈的水是清明的心，浑浊的水是被欲望和恐惧遮蔽的心。你的"音频归纳者"是你更高自我的声音，它说："停下来，检查泉源的质量，将你的耳朵调谐到寂静，然后黎明就会到来。"',
    '这篇文章是我在 Buddha\'s Wisdom Chat 上的第一篇文章。我希望它成为邀请你探索自己的梦境、直觉和佛教平行的一个邀请。\n\n我们从梦中学到了什么？\n\n1. 从科学角度来看——音频归纳者可能是技术专家，归纳主义者是经验方法的支持者。\n2. 从佛教角度来看——归纳是个人经验的道路，听闻是实践的基础，黎明是觉悟的目标。\n3. 象征性地——你的梦建议你停止从浑浊的源头（旧习惯）汲取智慧，转而转向寂静和观察。',
  ],
  ja: [
    '最近、夢を見ました。車を止めて水差しに水を入れようとしましたが、道路の下には排水管があり、濁った池に水を供給していました。前日、夢の中で奇妙な言葉を聞きました——「オーディオインダクショニスト」。まるで賢者が言ったかのような響きで、私は目を覚まして疑問に思いました：「これは何か？そんな用語は存在するのか？なぜ夢に出てきたのか？」\n\n科学的視点と仏教哲学に従って分析することを決意し——この言葉には深い意味が隠されており、このサイトの最初の記事の基盤になるかもしれないと気づきました。',
    '',
    '辞書に「オーディオインダクショニスト」の直接的な定義はありません。しかし、言葉を分解してみると：\n\n• オーディオ — 音、聴覚。\n• インダクション（帰納）— 物理学では磁場の生成、論理学では特殊から一般への推論。\n\n技術分野では「オーディオ誘導システム」という概念があります——聴覚障害者のための機器で、音を補聴器が受信できる電磁場に変換します。そのようなシステムの専門家はオーディオインダクショニストと呼べるでしょう——聴覚障害者のために「純粋な音」を調整するニッチな専門家です。',
    '「インダクショニスト」という言葉は、おそらく「帰納主義者」の変形です——帰納主義という哲学的方向性の支持者。この科学におけるアプローチは、帰納（多くの観察の一般化）を新しい知識を得る主要な方法と見なします。創始者はフランシス・ベーコンです。帰納主義者は、真理は既成の教義からではなく、経験から生まれると信じています。',
    'では、同じ概念を仏陀の教えのレンズを通して見てみましょう。',
    '仏教には有名なカラーマ経があります。そこで仏陀は言います：\n\n「聖典や教師に書かれているからというだけの理由で信じてはいけません。自分自身の経験でテストし検証したことだけを信じなさい。」\n\nこれは純粋な帰納です！あなたは個人的な「データ」（感覚、苦しみ、喜び）を集め、心の本質について結論を導き出します。仏陀は盲目的な信仰を要求しません——実験するようにあなたを誘います。この意味で、すべての仏教徒は一種の「帰納主義者」であり、個人の経験を通じて真理を知ります。',
    '仏教では、教えを聞くこと（パーリ語：suta）と音（マントラ、鐘、呼吸）への注意が非常に重要視されています。ヴィパッサナー修行とはまさに、内的感覚に「耳を調律する」ことです。したがって、この用語の「オーディオ」はマインドフルネスを指す可能性があります——外の音だけでなく、自分の魂の声も聞く能力。',
    '仏教における悟りは、無明の闇を払う日の出に例えられます。この夜明けは突然起こるものではありません——長い「帰納的」実践の後に訪れます：日々、呼吸、思考、原因と結果（カルマの法則）を観察しながら、あなたは徐々に万物の無常という普遍的な洞察に到達します。',
    '二つの夢に戻りましょう。\n\n最初の夢（言葉）：「オーディオインダクショニスト」は、あなたの「聴覚」を内なる声に調律し、個人の経験（「帰納」）を通じて洞察（「夜明け」）に到達するのを助ける精神的な導師の比喩かもしれません。\n\n二番目の夢（池）：車を止める——人生の旅における一時停止。水差し——教えを受け入れる準備ができたあなたの心。道路の下のパイプと濁った池——あなたが「水」（知恵）を汲もうとしている古い習慣、不安、情報ノイズ。夢は警告します：停滞した沼から水を取ってはいけません。沈殿させなさい（瞑想）、そうすれば澄み渡るでしょう。\n\n仏教の象徴において、清らかな水は清らかな心であり、濁った水は欲望と恐怖に曇った心です。あなたの「オーディオインダクショニスト」はあなたの高次の自己の声であり、こう言います：「止まりなさい、源の質を確かめなさい、耳を静寂に調律しなさい、そうすれば夜明けが来るでしょう。」',
    'この記事は、Buddha\'s Wisdom Chat での私の最初の記事です。皆さん自身の夢や直感、仏教的な類似点を探求する招待状となることを願っています。\n\n夢から何を学んだでしょうか？\n\n1. 科学的観点から——オーディオインダクショニストは技術専門家であり、帰納主義者は実証方法の支持者です。\n2. 仏教的観点から——帰納は個人経験の道であり、聴聞は実践の基盤であり、夜明けは悟りの目標です。\n3. 象徴的に——あなたの夢は、濁った源（古い習慣）から知恵を汲むのをやめ、代わりに静寂と観察に目を向けることを示唆しています。',
  ],
  pt: [
    'Recentemente tive um sonho. Parei o carro para encher um jarro de água, mas debaixo da estrada havia um cano de drenagem que alimentava um lago turvo. No dia anterior, ouvi uma palavra estranha no meu sonho — "audioinduccionista". Soava como se tivesse sido dita por alguém sábio, e acordei com uma pergunta: "O que é isto? Esse termo existe? E por que veio a mim num sonho?"\n\nDecidi analisá-lo de uma perspetiva científica e de acordo com a filosofia budista — e percebi que esta palavra esconde um significado profundo que poderia tornar-se a base para o primeiro artigo deste site.',
    '',
    'Não há definição direta de "audioinduccionista" nos dicionários. No entanto, se decompusermos a palavra:\n\n• Áudio — som, audição.\n• Indução — em física, a geração de um campo magnético; em lógica, o raciocínio do particular para o geral.\n\nNo campo técnico, existe o conceito de "sistema de indução auditiva" — equipamento para pessoas com deficiência auditiva que converte som num campo eletromagnético captado por um aparelho auditivo. Um especialista em tais sistemas poderia ser chamado de audioinduccionista — um profissional de nicho que sintoniza o "som puro" para pessoas com problemas auditivos.',
    'A palavra "induccionista" é muito provavelmente uma variante de "indutivista" — um defensor da direção filosófica do indutivismo. Esta abordagem científica considera a indução (generalização de muitas observações) como o principal método de adquirir novo conhecimento. O fundador é Francis Bacon. Um indutivista acredita que a verdade nasce da experiência, não de dogmas prontos.',
    'Agora vejamos os mesmos conceitos através da lente dos ensinamentos do Buda.',
    'No Budismo, há o famoso Sutta Kalama, onde o Buda diz:\n\n"Não acreditem simplesmente porque está escrito nas escrituras ou dito por um mestre. Acreditem apenas no que testaram e verificaram na vossa própria experiência."\n\nIsto é indução pura! Vocês recolhem os vossos "dados" pessoais (sensações, sofrimentos, alegrias) e tiram conclusões sobre a natureza da mente. O Buda não exige fé cega — ele convida-vos a experimentar. Neste sentido, cada budista é uma espécie de "induccionista" que conhece a verdade através da experiência pessoal.',
    'No Budismo, grande importância é dada à escuta do ensinamento (páli: suta) e à atenção ao som (mantras, sinos, respiração). A prática de Vipassana é precisamente "sintonizar o ouvido" para as sensações internas. Assim, "áudio" no termo pode apontar para a atenção plena — a capacidade de ouvir não apenas sons externos mas também a voz da própria alma.',
    'A iluminação no Budismo é frequentemente comparada ao nascer do sol que dissipa a escuridão da ignorância. Esta aurora não acontece de repente — chega após uma longa prática "indutiva": dia após dia observando a respiração, os pensamentos, causas e efeitos (a lei do karma), gradualmente chega-se à compreensão universal da impermanência de todas as coisas.',
    'Voltemos aos dois sonhos.\n\nPrimeiro sonho (a palavra): "Audioinduccionista" pode ser uma metáfora de um mentor espiritual que sintoniza a sua "audição" com a voz interior e ajuda, através da experiência pessoal ("indução"), a chegar à compreensão ("amanhecer").\n\nSegundo sonho (o lago): Parar o carro — uma pausa na jornada da vida. O jarro — a sua mente, pronta para receber o ensinamento. O cano debaixo da estrada e o lago turvo — velhos hábitos, ansiedades, ruído informacional do qual tenta extrair "água" (sabedoria). O sonho adverte: não tire água de um pântano estagnado. Deixe-a assentar (meditação), e ela se tornará clara.\n\nNo simbolismo budista, água clara é uma mente clara, e água turva é uma mente obscurecida por desejos e medos. O seu "audioinduccionista" é a voz do seu Ser superior, que diz: "Pare, verifique a qualidade da fonte, sintonize o ouvido ao silêncio, e então o amanhecer virá."',
    'Este artigo é o meu primeiro no Buddha\'s Wisdom Chat. Quero que seja um convite para explorar os seus próprios sonhos, intuição e paralelos budistas.\n\nO que aprendemos com o sonho?\n\n1. De uma perspetiva científica — um audioinduccionista pode ser um especialista técnico, e um induccionista um defensor do método empírico.\n2. De uma perspetiva budista — indução é o caminho da experiência pessoal, escuta é a base da prática, e o amanhecer é o objetivo da iluminação.\n3. Simbolicamente — o seu sonho sugere que pare de extrair sabedoria de fontes turvas (velhos hábitos) e em vez disso se volte para o silêncio e a observação.',
  ],
  th: [
    'เมื่อเร็วๆ นี้ฉันฝัน ฉันจอดรถเพื่อจะตักน้ำใส่เหยือก แต่ใต้ถนนมีท่อระบายน้ำที่ป้อนน้ำให้กับสระน้ำขุ่น ก่อนหน้านั้นหนึ่งวัน ฉันได้ยินคำแปลกๆ ในความฝัน — "นักอุปนัยเสียง" มันฟังดูเหมือนมีคนฉลาดพูดออกมา และฉันตื่นขึ้นมาพร้อมกับคำถาม: "นี่คืออะไร? มีคำนี้จริงหรือ? และทำไมมันถึงมาในความฝันของฉัน?"\n\nฉันตัดสินใจวิเคราะห์จากมุมมองทางวิทยาศาสตร์และตามหลักปรัชญาพุทธศาสนา — และตระหนักว่าคำนี้ซ่อนความหมายลึกซึ้งที่อาจเป็นพื้นฐานสำหรับบทความแรกบนเว็บไซต์นี้',
    '',
    'ไม่มีคำจำกัดความโดยตรงของ "นักอุปนัยเสียง" ในพจนานุกรม อย่างไรก็ตาม หากเราแยกคำออกเป็นส่วนๆ:\n\n• เสียง — การได้ยิน\n• อุปนัย — ในฟิสิกส์คือการเหนี่ยวนำสนามแม่เหล็ก; ในตรรกะคือการให้เหตุผลจากส่วนย่อยไปหาส่วนรวม\n\nในสาขาเทคนิค มีแนวคิดเรื่อง "ระบบเหนี่ยวนำเสียง" — อุปกรณ์สำหรับผู้บกพร่องทางการได้ยินที่แปลงเสียงเป็นสนามแม่เหล็กไฟฟ้าที่เครื่องช่วยฟังรับได้ ผู้เชี่ยวชาญในระบบดังกล่าวอาจเรียกว่านักอุปนัยเสียง — ผู้เชี่ยวชาญเฉพาะทางที่ปรับ "เสียงบริสุทธิ์" สำหรับผู้ที่มีปัญหาการได้ยิน',
    'คำว่า "นักอุปนัย" น่าจะเป็นอีกแบบหนึ่งของ "นักอุปนัยนิยม" — ผู้สนับสนุนทิศทางปรัชญาของอุปนัยนิยม แนวทางในวิทยาศาสตร์นี้ถือว่าอุปนัย (การสรุปจากการสังเกตหลายครั้ง) เป็นวิธีการหลักในการได้รับความรู้ใหม่ ผู้ก่อตั้งคือฟรานซิส เบคอน นักอุปนัยนิยมเชื่อว่าความจริงเกิดจากประสบการณ์ ไม่ใช่จากหลักคำสอนสำเร็จรูป',
    'ตอนนี้เรามาดูแนวคิดเดียวกันผ่านเลนส์ของคำสอนของพระพุทธเจ้า',
    'ในพุทธศาสนา มีพระสูตรกาลามะที่มีชื่อเสียง ซึ่งพระพุทธเจ้าตรัสว่า:\n\n"อย่าเชื่อเพียงเพราะมีกล่าวไว้ในคัมภีร์หรือโดยครูบาอาจารย์ จงเชื่อเฉพาะสิ่งที่ท่านได้ทดสอบและพิสูจน์แล้วในประสบการณ์ของตนเอง"\n\nนี่คืออุปนัยแท้! คุณรวบรวม "ข้อมูล" ส่วนตัว (ความรู้สึก ความทุกข์ ความสุข) และสรุปเกี่ยวกับธรรมชาติของจิต พระพุทธเจ้าไม่ต้องการความเชื่อแบบสุ่มสี่สุ่มห้า — พระองค์เชิญชวนให้คุณทดลอง ในแง่นี้ พุทธศาสนิกชนทุกคนเป็น "นักอุปนัย" ชนิดหนึ่งที่รู้ความจริงผ่านประสบการณ์ส่วนตัว',
    'ในพุทธศาสนา การฟังคำสอน (บาลี: สุตะ) และการใส่ใจเสียง (บทสวด ระฆัง ลมหายใจ) มีความสำคัญอย่างยิ่ง การปฏิบัติวิปัสสนาคือการ "ปรับหู" ให้รับรู้ความรู้สึกภายใน ดังนั้น "เสียง" ในคำนี้อาจชี้ไปที่สติ — ความสามารถในการได้ยินไม่เพียงแต่เสียงภายนอกแต่ยังรวมถึงเสียงของจิตวิญญาณตนเอง',
    'การตรัสรู้ในพุทธศาสนามักถูกเปรียบเทียบกับพระอาทิตย์ขึ้นที่ขจัดความมืดแห่งอวิชชา รุ่งอรุณนี้ไม่ได้เกิดขึ้นทันที — มันมาหลังจากการปฏิบัติ "แบบอุปนัย" อันยาวนาน: วันแล้ววันเล่าสังเกตลมหายใจ ความคิด เหตุและผล (กฎแห่งกรรม) คุณค่อยๆ มาถึงความเข้าใจสากลเกี่ยวกับความไม่เที่ยงของสรรพสิ่ง',
    'กลับมาที่ความฝันทั้งสอง\n\nความฝันแรก (คำ): "นักอุปนัยเสียง" อาจเป็นอุปมาของที่ปรึกษาทางจิตวิญญาณที่ปรับ "การได้ยิน" ของคุณให้รับเสียงภายใน และช่วยคุณผ่านประสบการณ์ส่วนตัว ("อุปนัย") ให้ถึงความเข้าใจ ("รุ่งอรุณ")\n\nความฝันที่สอง (สระน้ำ): การจอดรถ — การหยุดพักบนเส้นทางชีวิต เหยือก — จิตใจของคุณพร้อมรับคำสอน ท่อใต้ถนนและสระน้ำขุ่น — นิสัยเก่า ความกังวล เสียงรบกวนของข้อมูลที่คุณพยายามตัก "น้ำ" (ปัญญา) ความฝันเตือน: อย่าเอาน้ำจากบึงนิ่ง ปล่อยให้มันตกตะกอน (สมาธิ) แล้วมันจะใสสะอาด\n\nในสัญลักษณ์ทางพุทธศาสนา น้ำใสคือจิตที่แจ่มใส และน้ำขุ่นคือจิตที่ถูกบดบังด้วยตัณหาและความกลัว "นักอุปนัยเสียง" ของคุณคือเสียงของตัวตนที่สูงกว่าซึ่งพูดว่า: "หยุด ตรวจสอบคุณภาพของแหล่งที่มา ปรับหูของคุณให้รับความเงียบ แล้วรุ่งอรุณจะมาถึง"',
    'บทความนี้เป็นบทความแรกของฉันบน Buddha\'s Wisdom Chat ฉันต้องการให้มันเป็นคำเชิญให้สำรวจความฝัน สัญชาตญาณ และความคล้ายคลึงทางพุทธศาสนาของคุณเอง\n\nเราเรียนรู้อะไรจากความฝัน?\n\n1. จากมุมมองทางวิทยาศาสตร์ — นักอุปนัยเสียงอาจเป็นผู้เชี่ยวชาญด้านเทคนิค และนักอุปนัยเป็นผู้สนับสนุนวิธีการเชิงประจักษ์\n2. จากมุมมองทางพุทธศาสนา — อุปนัยเป็นเส้นทางของประสบการณ์ส่วนตัว การฟังเป็นพื้นฐานของการปฏิบัติ และรุ่งอรุณเป็นเป้าหมายของการตรัสรู้\n3. ในเชิงสัญลักษณ์ — ความฝันของคุณแนะนำให้คุณหยุดตักปัญญาจากแหล่งที่มืดมัว (นิสัยเก่า) และหันไปสู่ความเงียบและการสังเกตแทน',
  ],
  vi: [
    'Gần đây tôi có một giấc mơ. Tôi dừng xe để lấy nước vào một cái bình, nhưng dưới con đường có một ống thoát nước chảy vào một cái ao đục ngầu. Một ngày trước đó, tôi nghe thấy một từ lạ trong giấc mơ — "người quy nạp âm thanh". Nó nghe như được nói bởi một người khôn ngoan, và tôi thức dậy với một câu hỏi: "Đây là gì? Thuật ngữ này có tồn tại không? Và tại sao nó lại đến với tôi trong giấc mơ?"\n\nTôi quyết định phân tích nó từ góc độ khoa học và theo triết lý Phật giáo — và nhận ra rằng từ này ẩn chứa một ý nghĩa sâu sắc có thể trở thành nền tảng cho bài viết đầu tiên trên trang web này.',
    '',
    'Không có định nghĩa trực tiếp về "người quy nạp âm thanh" trong từ điển. Tuy nhiên, nếu chúng ta phân tích từ này:\n\n• Âm thanh — thính giác.\n• Quy nạp — trong vật lý là tạo ra từ trường; trong logic là suy luận từ cái riêng đến cái chung.\n\nTrong lĩnh vực kỹ thuật, có khái niệm "hệ thống cảm ứng âm thanh" — thiết bị cho người khiếm thính chuyển đổi âm thanh thành trường điện từ mà máy trợ thính có thể thu nhận. Một chuyên gia về hệ thống như vậy có thể được gọi là người quy nạp âm thanh — một chuyên gia thích hợp điều chỉnh "âm thanh tinh khiết" cho người có vấn đề về thính giác.',
    'Từ "người theo chủ nghĩa quy nạp" rất có thể là một biến thể của "người theo thuyết quy nạp" — một người ủng hộ hướng triết học của thuyết quy nạp. Cách tiếp cận này trong khoa học coi quy nạp (khái quát hóa nhiều quan sát) là phương pháp chính để thu nhận kiến thức mới. Người sáng lập là Francis Bacon. Một người theo thuyết quy nạp tin rằng sự thật sinh ra từ kinh nghiệm, không phải từ những giáo điều có sẵn.',
    'Bây giờ chúng ta hãy nhìn vào các khái niệm tương tự qua lăng kính giáo lý của Đức Phật.',
    'Trong Phật giáo, có Kinh Kalama nổi tiếng, nơi Đức Phật nói:\n\n"Đừng tin chỉ vì nó được nói trong kinh điển hoặc bởi một bậc thầy. Chỉ tin những gì bạn đã tự kiểm tra và xác minh trong kinh nghiệm của chính mình."\n\nĐây là quy nạp thuần túy! Bạn thu thập "dữ liệu" cá nhân của mình (cảm giác, khổ đau, niềm vui) và rút ra kết luận về bản chất của tâm trí. Đức Phật không đòi hỏi đức tin mù quáng — Ngài mời bạn thực nghiệm. Theo nghĩa này, mọi Phật tử đều là một loại "người quy nạp", người biết sự thật thông qua kinh nghiệm cá nhân.',
    'Trong Phật giáo, việc lắng nghe giáo pháp (Pali: suta) và chú ý đến âm thanh (thần chú, chuông, hơi thở) được coi trọng rất lớn. Thực hành Vipassana chính là "chỉnh tai" để cảm nhận các cảm giác bên trong. Vì vậy, "âm thanh" trong thuật ngữ có thể chỉ sự chánh niệm — khả năng nghe không chỉ âm thanh bên ngoài mà còn cả tiếng nói của tâm hồn mình.',
    'Giác ngộ trong Phật giáo thường được so sánh với mặt trời mọc xua tan bóng tối của vô minh. Bình minh này không đến đột ngột — nó đến sau một thời gian dài thực hành "quy nạp": ngày qua ngày quan sát hơi thở, suy nghĩ, nguyên nhân và kết quả (luật nhân quả), bạn dần dần đạt đến cái nhìn sâu sắc phổ quát về tính vô thường của vạn vật.',
    'Hãy quay lại hai giấc mơ.\n\nGiấc mơ thứ nhất (từ): "Người quy nạp âm thanh" có thể là một ẩn dụ cho một người cố vấn tinh thần, người điều chỉnh "thính giác" của bạn với tiếng nói bên trong và giúp bạn, thông qua kinh nghiệm cá nhân ("quy nạp"), đạt đến sự thấu hiểu ("bình minh").\n\nGiấc mơ thứ hai (ao nước): Dừng xe — một khoảng dừng trên hành trình cuộc đời. Cái bình — tâm trí bạn, sẵn sàng tiếp nhận giáo lý. Ống dẫn dưới đường và ao đục ngầu — thói quen cũ, lo lắng, tiếng ồn thông tin mà bạn cố gắng lấy "nước" (trí tuệ). Giấc mơ cảnh báo: đừng lấy nước từ đầm lầy tù đọng. Hãy để nó lắng xuống (thiền định), và nó sẽ trở nên trong vắt.\n\nTrong biểu tượng Phật giáo, nước trong là tâm trí sáng suốt, và nước đục là tâm trí bị che mờ bởi dục vọng và sợ hãi. "Người quy nạp âm thanh" của bạn là tiếng nói của bản ngã cao hơn, nói rằng: "Hãy dừng lại, kiểm tra chất lượng của nguồn, điều chỉnh tai bạn vào sự im lặng, và rồi bình minh sẽ đến."',
    'Bài viết này là bài viết đầu tiên của tôi trên Buddha\'s Wisdom Chat. Tôi muốn nó trở thành lời mời khám phá những giấc mơ, trực giác và những điểm tương đồng Phật giáo của riêng bạn.\n\nChúng ta đã học được gì từ giấc mơ?\n\n1. Từ góc độ khoa học — người quy nạp âm thanh có thể là một chuyên gia kỹ thuật, và người theo chủ nghĩa quy nạp là người ủng hộ phương pháp thực nghiệm.\n2. Từ góc độ Phật giáo — quy nạp là con đường của kinh nghiệm cá nhân, lắng nghe là nền tảng của thực hành, và bình minh là mục tiêu của giác ngộ.\n3. Về mặt biểu tượng — giấc mơ của bạn gợi ý bạn ngừng lấy trí tuệ từ những nguồn đục ngầu (thói quen cũ) và thay vào đó hãy hướng đến sự im lặng và quan sát.',
  ],
}

export const conclusions: Record<string, string> = {
  ru: 'Будда говорил: «Будьте сами себе светильниками». Возможно, «аудиоиндукционист» во сне — это и есть ваш внутренний светильник, который напоминает, что истина познаётся через собственное внимательное слушание жизни.\n\nЕсли вам тоже снятся странные слова или образы — не спешите их отбрасывать. Попробуйте разобрать их, как мы разобрали это слово. Возможно, они несут послание от вашей глубинной мудрости.',
  en: 'The Buddha said: "Be a lamp unto yourselves." Perhaps the "audioinductionist" in the dream is your inner lamp, reminding you that truth is realized through your own attentive listening to life.\n\nIf you too dream of strange words or images — do not rush to discard them. Try to analyze them as we analyzed this word. Perhaps they carry a message from your deep wisdom.',
  hi: 'बुद्ध ने कहा: "अपने स्वयं के दीपक बनो।" शायद सपने में "ऑडियोइंडक्शनिस्ट" आपका आंतरिक दीपक है, जो आपको याद दिलाता है कि सत्य जीवन को अपने स्वयं के चौकस श्रवण के माध्यम से महसूस किया जाता है।\n\nयदि आप भी अजीब शब्दों या छवियों का सपना देखते हैं — उन्हें त्यागने में जल्दबाजी न करें। उन्हें विश्लेषण करने का प्रयास करें जैसे हमने इस शब्द का विश्लेषण किया। शायद वे आपकी गहरी बुद्धि से एक संदेश ले जाते हैं।',
  es: 'Buda dijo: "Sed una lámpara para vosotros mismos." Quizás el "audioinduccionista" en el sueño es vuestra lámpara interior, que os recuerda que la verdad se realiza a través de vuestra propia escucha atenta de la vida.\n\nSi también soñáis con palabras o imágenes extrañas — no os apresuréis a descartarlas. Intentad analizarlas como analizamos esta palabra. Quizás llevan un mensaje de vuestra sabiduría profunda.',
  fr: 'Le Bouddha a dit : « Soyez une lampe pour vous-mêmes. » Peut-être que l\'« audioinductionniste » dans le rêve est votre lampe intérieure, vous rappelant que la vérité se réalise par votre propre écoute attentive de la vie.\n\nSi vous rêvez aussi de mots ou d\'images étranges — ne vous précipitez pas à les rejeter. Essayez de les analyser comme nous avons analysé ce mot. Peut-être portent-ils un message de votre sagesse profonde.',
  de: 'Der Buddha sagte: "Seid euch selbst ein Licht." Vielleicht ist der "Audioinduktionist" im Traum euer inneres Licht, das euch daran erinnert, dass Wahrheit durch das eigene aufmerksame Zuhören des Lebens verwirklicht wird.\n\nWenn auch ihr von seltsamen Wörtern oder Bildern träumt — beeilt euch nicht, sie zu verwerfen. Versucht, sie zu analysieren, wie wir dieses Wort analysiert haben. Vielleicht tragen sie eine Botschaft eurer tiefen Weisheit.',
  zh: '佛陀说："做自己的明灯。"也许梦中的"音频归纳者"就是您内心的明灯，提醒您真理是通过自己对生命的专注聆听而实现的。\n\n如果您也梦见奇怪的词语或图像——不要急于抛弃它们。试着像我们分析这个词一样分析它们。也许它们承载着来自您深层智慧的信息。',
  ja: '仏陀は言いました：「自分自身を灯明とせよ。」おそらく夢の中の「オーディオインダクショニスト」はあなたの内なる灯りであり、真理は人生に対するあなた自身の注意深い聴聞によって実現されることを思い出させてくれます。\n\nもしあなたも奇妙な言葉やイメージを夢に見たら——急いで捨て去らないでください。私たちがこの言葉を分析したように、それらを分析してみてください。おそらくそれらはあなたの深い知恵からのメッセージを運んでいます。',
  pt: 'O Buda disse: "Sede uma lâmpada para vós mesmos." Talvez o "audioinduccionista" no sonho seja a vossa lâmpada interior, lembrando-vos que a verdade se realiza através da vossa própria escuta atenta da vida.\n\nSe também sonhais com palavras ou imagens estranhas — não vos apresseis a descartá-las. Tentai analisá-las como analisamos esta palavra. Talvez elas carreguem uma mensagem da vossa sabedoria profunda.',
  th: 'พระพุทธเจ้าตรัสว่า "จงเป็นดวงประทีปแก่ตนเอง" บางที "นักอุปนัยเสียง" ในความฝันคือดวงประทีปภายในของคุณ ที่เตือนว่าความจริงเกิดขึ้นได้ผ่านการฟังชีวิตอย่างตั้งใจของคุณเอง\n\nหากคุณฝันถึงคำพูดหรือภาพแปลกๆ เช่นกัน — อย่ารีบปฏิเสธมัน ลองวิเคราะห์มันเหมือนที่เราวิเคราะห์คำนี้ บางทีมันอาจนำข้อความจากปัญญาอันลึกซึ้งของคุณ',
  vi: 'Đức Phật đã nói: "Hãy thắp đuốc lên mà đi." Có lẽ "người quy nạp âm thanh" trong giấc mơ là ngọn đèn nội tâm của bạn, nhắc nhở bạn rằng sự thật được nhận ra thông qua việc lắng nghe cuộc sống một cách chăm chú của chính bạn.\n\nNếu bạn cũng mơ thấy những từ ngữ hay hình ảnh kỳ lạ — đừng vội gạt bỏ chúng. Hãy thử phân tích chúng như chúng ta đã phân tích từ này. Biết đâu chúng mang một thông điệp từ trí tuệ sâu thẳm của bạn.',
  ko: '부처님께서 말씀하셨습니다: "너희 자신을 등불로 삼아라." 아마도 꿈속의 "오디오귀납주의자"는 당신의 내면의 등불이며, 진리가 당신 자신의 삶에 대한 주의 깊은 경청을 통해 실현된다는 것을 상기시켜 줍니다.\n\n당신도 이상한 단어나 이미지를 꾼다면 — 서둘러 버리지 마십시오. 우리가 이 단어를 분석한 것처럼 그것들을 분석해 보십시오. 아마도 그것들은 당신의 깊은 지혜로부터 온 메시지를 담고 있을 것입니다.',
  id: 'Buddha bersabda: "Jadilah pelita bagi dirimu sendiri." Mungkin "audioinduksionis" dalam mimpi adalah pelita batin Anda, mengingatkan Anda bahwa kebenaran diwujudkan melalui pendengaran penuh perhatian Anda sendiri terhadap kehidupan.\n\nJika Anda juga bermimpi tentang kata-kata atau gambar aneh — jangan terburu-buru membuangnya. Cobalah menganalisisnya seperti kita menganalisis kata ini. Mungkin mereka membawa pesan dari kebijaksanaan mendalam Anda.',
  ms: 'Buddha bersabda: "Jadilah lampu kepada dirimu sendiri." Mungkin "audioinduksionis" dalam mimpi adalah lampu dalaman anda, mengingatkan anda bahawa kebenaran direalisasikan melalui pendengaran penuh perhatian anda sendiri terhadap kehidupan.\n\nJika anda juga bermimpi tentang perkataan atau imej pelik — jangan tergesa-gesa membuangnya. Cuba analisisnya seperti kita menganalisis perkataan ini. Mungkin ia membawa mesej dari kebijaksanaan mendalam anda.',
  si: 'බුදුරජාණන් වහන්සේ මෙසේ වදාළ සේක: "තමාටම පහනක් වන්න." සමහරවිට සිහිනයේ "ශ්‍රව්‍ය ප්‍රේරකවාදී" යනු ඔබේ අභ්‍යන්තර පහන වන අතර, එය ඔබට මතක් කර දෙන්නේ සත්‍යය ජීවිතයට ඔබේම අවධානයෙන් සවන් දීම තුළින් අවබෝධ වන බවයි.\n\nඔබත් අමුතු වචන හෝ පින්තූර ගැන සිහින දකිනවා නම් — ඒවා ඉවත දැමීමට ඉක්මන් නොවන්න. අපි මෙම වචනය විශ්ලේෂණය කළාක් මෙන් ඒවා විශ්ලේෂණය කිරීමට උත්සාහ කරන්න. සමහරවිට ඒවා ඔබේ ගැඹුරු ප්‍රඥාවෙන් පණිවිඩයක් ගෙන එයි.',
  my: 'မြတ်စွာဘုရားက ဤသို့မိန့်ကြားတော်မူသည်: "မိမိကိုယ်ကို ဆီမီးအဖြစ်ထားကြလော့"။ အိပ်မက်ထဲရှိ "အသံလျှပ်ကူးဝါဒီ" သည် သင်၏အတွင်းစိတ်ဆီမီးဖြစ်နိုင်ပြီး အမှန်တရားသည် ဘဝကို မိမိကိုယ်တိုင် ဂရုတစိုက်နားထောင်ခြင်းဖြင့် သိရှိနိုင်သည်ကို သတိပေးနေသည်။\n\nသင်လည်း ထူးဆန်းသောစကားလုံးများ သို့မဟုတ် ပုံရိပ်များကို အိပ်မက်မက်ပါက — ၎င်းတို့ကို စွန့်ပစ်ရန် မလျင်ပါနှင့်။ ကျွန်ုပ်တို့ ဤစကားလုံးကို ခွဲခြမ်းစိတ်ဖြာသကဲ့သို့ ၎င်းတို့ကို ခွဲခြမ်းစိတ်ဖြာကြည့်ပါ။ ၎င်းတို့သည် သင်၏နက်နဲသောဉာဏ်ပညာမှ သတင်းစကားတစ်ခုကို သယ်ဆောင်လာနိုင်သည်။',
  ne: 'बुद्धले भन्नुभयो: "आफैं आफ्नो दीपक बन।" सपनामा "अडियोइन्डक्सनिस्ट" तपाईंको आन्तरिक दीपक हुन सक्छ, जसले तपाईंलाई सम्झाउँछ कि सत्य जीवनको आफ्नै ध्यानपूर्वक सुनाइ मार्फत प्राप्त हुन्छ।\n\nयदि तपाईं पनि अनौठो शब्द वा छविहरूको सपना देख्नुहुन्छ भने — तिनीहरूलाई त्याग्न हतार नगर्नुहोस्। हामीले यो शब्द विश्लेषण गरेजस्तै तिनीहरूलाई विश्लेषण गर्ने प्रयास गर्नुहोस्। हुनसक्छ तिनीहरूले तपाईंको गहिरो बुद्धिबाट सन्देश बोकेका छन्।',
  bo: 'སངས་རྒྱས་ཀྱིས། "རང་ཉིད་རང་གི་མར་མེར་གྱིས།" ཞེས་གསུངས། རྨི་ལམ་ནང་གི་"སྒྲ་ཐེབས་ལེན་པ" ནི་ཁྱེད་ཀྱི་ནང་གི་མར་མེ་ཡིན་ཏེ། བདེན་པ་ནི་ཁྱེད་ཀྱིས་རང་ཉིད་ཀྱི་འཚོ་བར་བསམ་གཞིགས་ཀྱིས་ཉན་པ་ལས་རྟོགས་པར་དྲན་སྐུལ་བྱེད།\n\nགལ་ཏེ་ཁྱེད་ཀྱང་སྒྲ་མི་སྙན་དང་རྣམ་པར་རྨི་ལམ་དུ་མཐོང་ན། མྱུར་དུ་དོར་བར་མ་གནང་། ང་ཚོས་ཚིག་འདི་དཔྱད་པ་ལྟར་དེ་དག་དཔྱད་པར་འབད། དེ་དག་གིས་ཁྱེད་ཀྱི་གཏིང་ཟབ་ཀྱི་ཤེས་རབ་ལས་ཕྲིན་ཡིག་སྐྱེལ་གྱི་ཡོད།',
}
